
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - visitors.example.com
  resources:
  - vistorsapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - visitors.example.com
  resources:
  - vistorsapps/finalizers
  verbs:
  - update
- apiGroups:
  - visitors.example.com
  resources:
  - vistorsapps/status
  verbs:
  - get
  - patch
  - update
